class Board:
    def __init__(self):
        self.sites = {
            0: ['GO'],
            1: ['OLD KENT ROAD'],
            2: ['COMMUNITY CHEST'],
            3: ['WHITECHAPELROAD'],
            4: ['INCOME TAX'],
            5: ['KINGS CROSS STATION'],
            6: ['THE ANGLE ISLINGITON'],
            7: ['CHANCE'],
            8: ['EUSTON ROAD'],
            9: ['PENTONVILLE ROAD'],
            10: ['JAIL'],
            11: ['PALL MALL'],
            12: ['ELECTRIC COMPANY'],
            13: ['WHITEHALL'],
            14: ["NORTHUMBERL'D STATION"],
            15: ['MARYLEBONE STATION'],
            16: ['BOW STREET'],
            17: ['COMMUNITY CHEST'],
            18: ['MARLBROUGH STREE'],
            19: ['VINE STREET'],
            20: ['FREE PARKING'],
            21: ['STRAND'],
            22: ['CHANCE'],
            23: ['FLEET STREET'],
            24: ['TRAFALGAR SQUARE'],
            25: ['FENCHURCH STREET STATION'],
            26: ['LEICESTER SQUARE'],
            27: ['CONVENTRY STREET'],
            28: ['WATER WORKS'],
            29: ['PICCADILLY'],
            30: ['GO TO JAIL'],
            31: ['REGENT STREET'],
            32: ['OXFORD STREET'],
            33: ['COMMUNITY CHEST'],
            34: ['BOND STREET'],
            35: ['LIVERPOOL STREET STATION'],
            36: ['CHANCE'],
            37: ['PARK LANE'],
            38: ['SUPER TAX'],
            39: ['MAYFAIR']}
